---
process:
  contrast: before # before or after (stretching)
  grey_mode: normal # normal or lessback or moreback
  rgb_adjust: no
  alpha: 1.
  gamma_lum: 1.
use_bands:
<<<<<<< HEAD
  # - VISIONS_J
  # - VISIONS_H
  # - VISIONS_Ks
  - IRAC1
  - IRAC2
  - IRAC3
  - IRAC4
  - MIPS1
  - PACS70
  - PACS100
  - PACS160
  - SPIRE250
  - SPIRE350
  - SPIRE500
=======
  - VISIONS_J
  - VISIONS_H
  - VISIONS_Ks
    #  - IRAC1
    #  - IRAC2
    #  - IRAC3
    #  - IRAC4
    #  - MIPS1
>>>>>>> 93903f9a77e075f501865acef0c2cd0fc0f5a945
combinations_test:
  - ["i3", "Ks", "J" ]
  - ["i4", "i3", "i2"]
  - ["m1", "Ks", "J" ]
  - ["m1", "i3", "Ks"]
combinations_hand:
  - ["Ks", "H" , "J" ]
    #  - ["i3", "Ks", "J" ]
    #  - ["i3", "i2", "Ks"]
    #  - ["m1", "Ks", "J" ]
    #  - ["m1", "i2", "Ks"]
    #  - ["m1", "i2", "Ks", "J" ]
combinations_all:
  - ["Ks", "H" , "J" ]
  - ["i3", "Ks", "J" ]
  - ["i4", "i3", "i2"]
  - ["i3", "i2", "J" ]
  - ["i3", "i2", "Ks"]
  - ["i3", "i2", "i1"]
  - ["m1", "Ks", "J" ]
  - ["m1", "i1", "J" ]
  - ["m1", "i2", "H" ]
  - ["m1", "i3", "H" ]
  - ["m1", "i2", "Ks"]
  - ["m1", "i3", "Ks"]
  - ["m1", "i4", "Ks"]
  - ["m1", "i4", "i2"]
combinations_one:
  - ["m1", "i4", "i2"]
combinations_some:
  - ["i4", "i3", "i2"]
  - ["i3", "i2", "i1"]
  - ["m1", "i4", "i2"]
  - ["p16", "p10", "p7"]
  - ["s50", "s35", "s25"]
  - ["s35", "p10", "m1"]
  - ["s50", "p7", "i1"]
  - ["s50", "m1", "i2"]
  - ["s25", "m1", "i4"]
  - ["s35", "i4", "i1"]
  - ["p16", "m1", "i2"]
  - ["p7", "m1", "i4"]
  - ["p7", "i4", "i1"]
combinations:
  - ['i3', 'i2', 'i1']
  - ['i4', 'i2', 'i1']
  - ['i4', 'i3', 'i1']
  - ['i4', 'i3', 'i2']
  - ['m1', 'i2', 'i1']
  - ['m1', 'i3', 'i1']
  - ['m1', 'i3', 'i2']
  - ['m1', 'i4', 'i1']
  - ['m1', 'i4', 'i2']
  - ['m1', 'i4', 'i3']
  - ['p7', 'i2', 'i1']
  - ['p7', 'i3', 'i1']
  - ['p7', 'i3', 'i2']
  - ['p7', 'i4', 'i1']
  - ['p7', 'i4', 'i2']
  - ['p7', 'i4', 'i3']
  - ['p7', 'm1', 'i1']
  - ['p7', 'm1', 'i2']
  - ['p7', 'm1', 'i3']
  - ['p7', 'm1', 'i4']
  - ['p10', 'i2', 'i1']
  - ['p10', 'i3', 'i1']
  - ['p10', 'i3', 'i2']
  - ['p10', 'i4', 'i1']
  - ['p10', 'i4', 'i2']
  - ['p10', 'i4', 'i3']
  - ['p10', 'm1', 'i1']
  - ['p10', 'm1', 'i2']
  - ['p10', 'm1', 'i3']
  - ['p10', 'm1', 'i4']
  - ['p10', 'p7', 'i1']
  - ['p10', 'p7', 'i2']
  - ['p10', 'p7', 'i3']
  - ['p10', 'p7', 'i4']
  - ['p10', 'p7', 'm1']
  - ['p16', 'i2', 'i1']
  - ['p16', 'i3', 'i1']
  - ['p16', 'i3', 'i2']
  - ['p16', 'i4', 'i1']
  - ['p16', 'i4', 'i2']
  - ['p16', 'i4', 'i3']
  - ['p16', 'm1', 'i1']
  - ['p16', 'm1', 'i2']
  - ['p16', 'm1', 'i3']
  - ['p16', 'm1', 'i4']
  - ['p16', 'p7', 'i1']
  - ['p16', 'p7', 'i2']
  - ['p16', 'p7', 'i3']
  - ['p16', 'p7', 'i4']
  - ['p16', 'p7', 'm1']
  - ['p16', 'p10', 'i1']
  - ['p16', 'p10', 'i2']
  - ['p16', 'p10', 'i3']
  - ['p16', 'p10', 'i4']
  - ['p16', 'p10', 'm1']
  - ['p16', 'p10', 'p7']
  - ['s25', 'i2', 'i1']
  - ['s25', 'i3', 'i1']
  - ['s25', 'i3', 'i2']
  - ['s25', 'i4', 'i1']
  - ['s25', 'i4', 'i2']
  - ['s25', 'i4', 'i3']
  - ['s25', 'm1', 'i1']
  - ['s25', 'm1', 'i2']
  - ['s25', 'm1', 'i3']
  - ['s25', 'm1', 'i4']
  - ['s25', 'p7', 'i1']
  - ['s25', 'p7', 'i2']
  - ['s25', 'p7', 'i3']
  - ['s25', 'p7', 'i4']
  - ['s25', 'p7', 'm1']
  - ['s25', 'p10', 'i1']
  - ['s25', 'p10', 'i2']
  - ['s25', 'p10', 'i3']
  - ['s25', 'p10', 'i4']
  - ['s25', 'p10', 'm1']
  - ['s25', 'p10', 'p7']
  - ['s25', 'p16', 'i1']
  - ['s25', 'p16', 'i2']
  - ['s25', 'p16', 'i3']
  - ['s25', 'p16', 'i4']
  - ['s25', 'p16', 'm1']
  - ['s25', 'p16', 'p7']
  - ['s25', 'p16', 'p10']
  - ['s35', 'i2', 'i1']
  - ['s35', 'i3', 'i1']
  - ['s35', 'i3', 'i2']
  - ['s35', 'i4', 'i1']
  - ['s35', 'i4', 'i2']
  - ['s35', 'i4', 'i3']
  - ['s35', 'm1', 'i1']
  - ['s35', 'm1', 'i2']
  - ['s35', 'm1', 'i3']
  - ['s35', 'm1', 'i4']
  - ['s35', 'p7', 'i1']
  - ['s35', 'p7', 'i2']
  - ['s35', 'p7', 'i3']
  - ['s35', 'p7', 'i4']
  - ['s35', 'p7', 'm1']
  - ['s35', 'p10', 'i1']
  - ['s35', 'p10', 'i2']
  - ['s35', 'p10', 'i3']
  - ['s35', 'p10', 'i4']
  - ['s35', 'p10', 'm1']
  - ['s35', 'p10', 'p7']
  - ['s35', 'p16', 'i1']
  - ['s35', 'p16', 'i2']
  - ['s35', 'p16', 'i3']
  - ['s35', 'p16', 'i4']
  - ['s35', 'p16', 'm1']
  - ['s35', 'p16', 'p7']
  - ['s35', 'p16', 'p10']
  - ['s35', 's25', 'i1']
  - ['s35', 's25', 'i2']
  - ['s35', 's25', 'i3']
  - ['s35', 's25', 'i4']
  - ['s35', 's25', 'm1']
  - ['s35', 's25', 'p7']
  - ['s35', 's25', 'p10']
  - ['s35', 's25', 'p16']
  - ['s50', 'i2', 'i1']
  - ['s50', 'i3', 'i1']
  - ['s50', 'i3', 'i2']
  - ['s50', 'i4', 'i1']
  - ['s50', 'i4', 'i2']
  - ['s50', 'i4', 'i3']
  - ['s50', 'm1', 'i1']
  - ['s50', 'm1', 'i2']
  - ['s50', 'm1', 'i3']
  - ['s50', 'm1', 'i4']
  - ['s50', 'p7', 'i1']
  - ['s50', 'p7', 'i2']
  - ['s50', 'p7', 'i3']
  - ['s50', 'p7', 'i4']
  - ['s50', 'p7', 'm1']
  - ['s50', 'p10', 'i1']
  - ['s50', 'p10', 'i2']
  - ['s50', 'p10', 'i3']
  - ['s50', 'p10', 'i4']
  - ['s50', 'p10', 'm1']
  - ['s50', 'p10', 'p7']
  - ['s50', 'p16', 'i1']
  - ['s50', 'p16', 'i2']
  - ['s50', 'p16', 'i3']
  - ['s50', 'p16', 'i4']
  - ['s50', 'p16', 'm1']
  - ['s50', 'p16', 'p7']
  - ['s50', 'p16', 'p10']
  - ['s50', 's25', 'i1']
  - ['s50', 's25', 'i2']
  - ['s50', 's25', 'i3']
  - ['s50', 's25', 'i4']
  - ['s50', 's25', 'm1']
  - ['s50', 's25', 'p7']
  - ['s50', 's25', 'p10']
  - ['s50', 's25', 'p16']
  - ['s50', 's35', 'i1']
  - ['s50', 's35', 'i2']
  - ['s50', 's35', 'i3']
  - ['s50', 's35', 'i4']
  - ['s50', 's35', 'm1']
  - ['s50', 's35', 'p7']
  - ['s50', 's35', 'p10']
  - ['s50', 's35', 'p16']
  - ['s50', 's35', 's25']
...
