---
process:
  contrast: before # before or after (stretching)
  grey_mode: normal # normal or lessback or moreback
  rgb_adjust: no
  alpha: 1.
  gamma_lum: 1.
use_bands:
  - VISIONS_J
  - VISIONS_H
  - VISIONS_Ks
    #  - IRAC1
    #  - IRAC2
    #  - IRAC3
    #  - IRAC4
    #  - MIPS1
combinations_test:
  - ["i3", "Ks", "J" ]
  - ["i4", "i3", "i2"]
  - ["m1", "Ks", "J" ]
  - ["m1", "i3", "Ks"]
combinations:
  - ["Ks", "H" , "J" ]
    #  - ["i3", "Ks", "J" ]
    #  - ["i3", "i2", "Ks"]
    #  - ["m1", "Ks", "J" ]
    #  - ["m1", "i2", "Ks"]
    #  - ["m1", "i2", "Ks", "J" ]
combinations_all:
  - ["Ks", "H" , "J" ]
  - ["i3", "Ks", "J" ]
  - ["i4", "i3", "i2"]
  - ["i3", "i2", "J" ]
  - ["i3", "i2", "Ks"]
  - ["i3", "i2", "i1"]
  - ["m1", "Ks", "J" ]
  - ["m1", "i1", "J" ]
  - ["m1", "i2", "H" ]
  - ["m1", "i3", "H" ]
  - ["m1", "i2", "Ks"]
  - ["m1", "i3", "Ks"]
  - ["m1", "i4", "Ks"]
...