---
process:
  contrast: before # before or after (stretching)
  grey_mode: normal # normal or lessback or moreback
  rgb_adjust: no
  alpha: 1.
  gamma_lum: 1.
use_bands:
  - VISIONS_J
  - VISIONS_H
  - VISIONS_Ks
  - IRAC1
  - IRAC2
  - IRAC3
  - IRAC4
  - MIPS1
combinations:
  - ["i3", "Ks", "J" ]
  - ["i4", "i3", "i2"]
  - ["m1", "Ks", "J" ]
  - ["m1", "i3", "Ks"]
combinations_t:
  - ["Ks", "H", "J" ]
...