---
general:
  filenames: ${image_name}_${band_name}
  # e.g. $band/fits/$name or ${image_name}_${band_name}
process:
  multiprocess: no      # no (default) or yes
  grey_mode: normal     # normal, lessback or moreback
  rgb_adjust: no        # no (default) or yes
  alpha: 1.             # float (default=1.), typ. 1-2
  gamma_lum: 1.         # float (default=1.), typ. 1-3
  clip: 10.             # float (default=10.)
  nanmode: max          # max (default) or median
  skymode: clipmedian   # median (default), clipmedian, quantile or debug
  maxmode: quantile     # quantile (default), max or debug
  slice: NULL           # NULL (default) or [wx, wy]
  equal_offset: .1      # float (default=.1)
  equal_norm: yes       # yes (default) or no
figure:
  titlemode: debug      # debug or pub
  include_suptitle: yes # yes (default) or no
  figsize: [3, 5.6]     # [col, row]
  centermark: no        # no (default) or yes
  gridlines: no         # no (default) or yes
use_bands:
  - VISION_J
  - VISION_H
  - VISION_Ks
  - IRAC1
  - IRAC2
  - IRAC3
  - IRAC4
  - MIPS1
combinations:
  - [i3, Ks, J ]
  - [i4, i3, i2]
  - [m1, Ks, J ]
  - [m1, i3, Ks]
  - [Ks, H , J ]
...