---
process:
  multiprocess: no
  grey_mode: normal # normal or lessback or moreback
  rgb_adjust: no
  alpha: 1.
  gamma_lum: 1.
  clip: 10
  nanmode: max
  skymode: clipmedian
  slice: None
  equal_offset: .1
  equal_norm: yes
figure:
  titlemode: debug # debug or pub
  include_suptitle: yes
  figsize: [3, 5.6]
use_bands:
  - VISION_J
  - VISION_H
  - VISION_Ks
  - IRAC1
  - IRAC2
  - IRAC3
  - IRAC4
  - MIPS1
combinations:
  - ["i3", "Ks", "J" ]
  - ["i4", "i3", "i2"]
  - ["m1", "Ks", "J" ]
  - ["m1", "i3", "Ks"]
  - ["Ks", "H" , "J" ]
...