---
!Configurator
general: !GeneralConfigurator
  filenames: ${image_name}_${band_name}.fits
  # e.g. $band_name/fits/$image_name.fits or ${image_name}_${band_name}.fits
  multiprocess: False    # False (default) or True
  jpeg_quality: 95       # see pillow documentation for details
process: !ProcessConfigurator
  grey_mode: normal      # normal, lessback or moreback
  rgb_adjust: False      # False (default) or True
  alpha: 1.              # float (default=1.), typ. 1-2
  gamma_lum: 1.          # float (default=1.), typ. 1-3
  clip: 10.              # float (default=10.)
  nanmode: max           # max (default) or median
  skymode: median        # median (default), clipmedian, quantile or debug
  maxmode: quantile      # quantile (default), max or debug
  slice: NULL            # NULL (default) or [wx, wy]
  equal_offset: .1       # float (default=.1)
  equal_norm: True       # True (default) or False
figures: !FiguresConfigurator
  titlemode: debug       # debug or pub
  include_suptitle: True # True (default) or False
  figsize: [3, 5.6]      # [col, row]
  max_cols: 4            # int (default=4)
  centermark: False      # False (default) or True
  gridlines: False       # False (default) or True
  additional_roi:        # each as [ra, dec] in decimal deg format
use_bands:
    - VISION_J
    - VISION_H
    - VISION_Ks
    - IRAC1
    - IRAC2
    - IRAC3
    - IRAC4
    - MIPS1
combinations:
    - [i3, Ks, J ]
    - [i4, i3, i2]
    - [m1, Ks, J ]
    - [m1, i3, Ks]
    - [Ks, H , J ]
...